[build]
  base = ""
  command = "npm run build"
  publish = "client/build"
  functions = "backend/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200